[toolchain]
channel = "1.82.0"
components = [ "rustfmt", "rust-analyzer" ]
targets = [ "x86_64-pc-windows-msvc", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "aarch64-apple-darwin"]
profile = "minimal"
